const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
const ADD_QUANTITY = 'ADD_QUANTITY';
const REMOVE_QUANTITY = 'REMOVE_QUANTITY';
const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
const ADD_ITEMS_TO_PREVIOUS_ORDER = 'ADD_ITEMS_TO_PREVIOUS_ORDER';

export {
  ADD_ITEM_TO_CART,
  ADD_QUANTITY,
  REMOVE_QUANTITY,
  REMOVE_ITEM_FROM_CART,
  ADD_ITEMS_TO_PREVIOUS_ORDER,
};
